/*
 * Analog VCO model for the minilogue xd replica (used for VCO1 and VCO2).
 *
 * Plain TS DSP class: no DOM, no worklet globals. Sample rate is injected.
 * Anti-aliasing strategy:
 *   - SAW:  2-point polyBLEP on every discontinuity. SHAPE subtracts a second
 *           BLEP'd saw whose edge spacing narrows toward half a period, so max
 *           shape is exactly saw(t) - saw(t+0.5) = a square wave: the morph
 *           attenuates EVEN harmonics toward a square-ish blend (spec §4,
 *           matches the hardware's audible SHAPE behaviour on SAW).
 *   - TRI:  polyBLAMP corners (2-point, integrated-BLEP) so the triangle stays
 *           clean under linear FM. SHAPE drives a smooth sine wavefolder
 *           (fold gain 1..8) blended in continuously - the fold curve is C-inf
 *           smooth, so added harmonics roll off quickly (band-limited enough).
 *   - SQR:  pulse, width 50% -> 5% with SHAPE, polyBLEP on both edges. The DC
 *           that pulse-width introduces is removed analytically (dc = 2*pw - 1)
 *           and the wave is peak-normalized so narrow pulses stay in [-1, 1].
 *   - Hard sync: fractional phase reset using the master's wrapFrac, plus a
 *           polyBLEP residual scaled by the actual naive-waveform step at the
 *           reset instant (the "after" half of the 2-point BLEP; the "before"
 *           half would belong to the already-emitted previous sample).
 *
 * Linear FM convention: effective freq = smoothed base freq + fmHz, clamped to
 * [-0.45*sr, +0.45*sr]. NEGATIVE effective frequency makes the phase run
 * BACKWARDS and wraps are handled in both directions (wrapped/wrapFrac fire on
 * backward wraps too). Reverse-direction output is generated by mirroring the
 * phase (u = 1 - t) so the polyBLEP branches stay time-forward and correct.
 *
 * Click avoidance: base freq and shape are one-pole smoothed per sample
 * (~0.35 ms / ~1 ms), wave changes crossfade over ~2 ms, and a gentle 1-pole
 * lowpass (~18 kHz) models analog edge softness. tick() allocates nothing.
 */

export const VCO_WAVE = { SQR: 0, TRI: 1, SAW: 2 } as const

export type VcoWaveId = (typeof VCO_WAVE)[keyof typeof VCO_WAVE]

const HALF_PI = Math.PI * 0.5
const TWO_PI = Math.PI * 2
const EPS_DT = 1e-9

function frac(x: number): number {
  return x - Math.floor(x)
}

/**
 * 2-point polyBLEP residual for a UNIT up-step, evaluated AFTER the edge.
 * tau = time since the edge in samples, in [0, 1). Multiply by the signed step
 * height and add to the naive waveform.
 */
function blepAfter(tau: number): number {
  const x = 1 - tau
  return -0.5 * x * x
}

/**
 * 2-point polyBLEP residual for a UNIT up-step, evaluated BEFORE the edge.
 * tau = (t - t_edge)/dt in [-1, 0).
 */
function blepBefore(tau: number): number {
  const x = tau + 1
  return 0.5 * x * x
}

/**
 * 2-point polyBLAMP residual for a UNIT slope increase (slope measured in
 * amplitude per sample). tau in [0,1) after / [-1,0) before the corner.
 */
function blampAfter(tau: number): number {
  const x = 1 - tau
  return (x * x * x) / 6
}

function blampBefore(tau: number): number {
  const x = tau + 1
  return (x * x * x) / 6
}

function flushDenormal(x: number): number {
  return x > -1e-18 && x < 1e-18 ? 0 : x
}

/**
 * Symmetric single wavefold at ±1 with a soft quadratic knee of radius r:
 * |v| ≤ 1−r passes, a C¹ parabola spans [1−r, 1+r] (peak 1 − r/2, matching
 * slopes ±1 at both ends), beyond reflects hard (y = 2 − |v|). r = 0 is the
 * hard fold. Models the xd TRI SHAPE (single fold per peak, measured
 * 2026-07-11; hard-reflection fits degrade at high drive — the analog knee
 * is soft).
 */
function softFold1(v: number, r: number): number {
  const s = v < 0 ? -1 : 1
  const a = s * v
  if (r > 1e-6) {
    const lo = 1 - r
    if (a <= lo) return v
    const e = a - lo
    if (e < 2 * r) return s * (lo + e - (e * e) / (2 * r))
    return s * (2 - a)
  }
  return a <= 1 ? v : s * (2 - a)
}

/** PolyBLEP sawtooth, edge (step of -2) at phase 0/1. t in [0,1]. */
function sawBl(t: number, adt: number, suppressWrapBlep: boolean): number {
  let y = 2 * t - 1
  if (adt > EPS_DT) {
    if (t < adt) {
      if (!suppressWrapBlep) y -= 2 * blepAfter(t / adt)
    } else if (t > 1 - adt) {
      y -= 2 * blepBefore((t - 1) / adt)
    }
  }
  return y
}

/** PolyBLEP pulse: +1 for t < pw else -1, rising edge at 0, falling at pw. */
function pulseBl(t: number, adt: number, pw: number, suppressWrapBlep: boolean): number {
  let y = t < pw ? 1 : -1
  if (adt > EPS_DT) {
    // Rising edge at phase 0 (step +2).
    if (t < adt) {
      if (!suppressWrapBlep) y += 2 * blepAfter(t / adt)
    } else if (t > 1 - adt) {
      y += 2 * blepBefore((t - 1) / adt)
    }
    // Falling edge at phase pw (step -2).
    const s = t - pw
    if (s >= 0) {
      if (s < adt) y -= 2 * blepAfter(s / adt)
    } else if (s > -adt) {
      y -= 2 * blepBefore(s / adt)
    }
  }
  return y
}

function triNaive(t: number): number {
  return t < 0.5 ? 4 * t - 1 : 3 - 4 * t
}

/** PolyBLAMP triangle: corners at phase 0 (slope +8/period) and 0.5 (-8). */
function triBl(t: number, adt: number, suppressWrapBlamp: boolean): number {
  let y = triNaive(t)
  if (adt > EPS_DT) {
    const k = 8 * adt // slope change in amplitude-per-sample units
    if (t < adt) {
      if (!suppressWrapBlamp) y += k * blampAfter(t / adt)
    } else if (t > 1 - adt) {
      y += k * blampBefore((t - 1) / adt)
    }
    const s = t - 0.5
    if (s >= 0) {
      if (s < adt) y -= k * blampAfter(s / adt)
    } else if (s > -adt) {
      y -= k * blampBefore(s / adt)
    }
  }
  return y
}

export class Vco {
  private readonly sr: number
  private readonly invSr: number
  private readonly maxFreq: number
  private readonly freqCoef: number
  private readonly shapeCoef: number
  private readonly lpCoef: number
  private readonly fadeLen: number

  private wave: number = VCO_WAVE.SAW
  private prevWave: number = VCO_WAVE.SAW
  private fadeCount = 0

  private freqTarget = 440
  private freqSm = 440
  private shapeTarget = 0
  private shapeSm = 0

  /**
   * SQR pulse width at SHAPE max (0..0.5); pw runs 0.5 -> pwMin over SHAPE.
   * A calibration target: the real xd narrows all the way to 0% = silence
   * (measured 2026-07-08); the historical replica guess floors at 5%.
   * Read live each sample so a profile switch needs no reconstruction.
   */
  pwMin = 0.05

  /*
   * Measured SHAPE morph models (minilogue xd D2, 2026-07-11) — injected by
   * the synth's voice exactly like pwMin: null keeps the original guessed
   * morphs bit-identical (the other synths never set these). Each fn maps the
   * SMOOTHED shape (0..1) to a model parameter; they are compiled profile
   * curves, cheap per sample.
   */
  /** SQR: shape -> pulse duty. Constant-swing pulse with real DC — no
   *  analytic DC removal, no peak normalization (both unfaithful; measured
   *  level ratio stays ~1.0 across the sweep where normalization predicts
   *  0.54). Widths below the BLEP transition fade out as with pwMin = 0. */
  sqrDutyFn: ((shape01: number) => number) | null = null
  /** TRI: shape -> single-fold drive g' (1 = none, 3 = exact x3 triple). */
  triDriveFn: ((shape01: number) => number) | null = null
  /** TRI: shape -> output level at the fold ceiling (1 at shape 0). */
  triLevelFn: ((shape01: number) => number) | null = null
  /** TRI: soft-fold knee radius (0 = hard reflection). */
  triKnee = 0
  /** SAW: shape -> reversal-mirror half-width w (0 = plain saw; 0.5 = full
   *  alternate-tooth time-mirror, the measured octave-down morph with exact
   *  half-wave antisymmetry at SHAPE max). The wave is saw(phi) except
   *  saw(2-phi) inside a window +-w*T centered on the alternate tooth
   *  boundary (D2 dense-sweep model, 2026-07-11). */
  sawMirrorWFn: ((shape01: number) => number) | null = null

  /** Half-rate divider state for the SAW mirror: flips on every wrap. */
  private chopParity = 1

  private phase = 0
  private _wrapped = false
  private _wrapFrac = 0

  private syncPending = false
  private syncFrac = 0

  private lp = 0

  constructor(sampleRate: number) {
    const sr = Number.isFinite(sampleRate) && sampleRate > 0 ? sampleRate : 48000
    this.sr = sr
    this.invSr = 1 / sr
    this.maxFreq = sr * 0.45
    // One-pole smoothing coefficients (~0.35 ms for pitch, ~1 ms for shape).
    this.freqCoef = 1 - Math.exp(-1 / (0.00035 * sr))
    this.shapeCoef = 1 - Math.exp(-1 / (0.001 * sr))
    // Analog edge softness: gentle 1-pole lowpass around 18 kHz.
    const fc = Math.min(18000, sr * 0.4)
    this.lpCoef = 1 - Math.exp((-TWO_PI * fc) / sr)
    // Wave-select crossfade length (~2 ms).
    this.fadeLen = Math.max(8, Math.round(0.002 * sr))
  }

  /** True if our phase wrapped (either direction, or was hard-sync reset) during the last tick. */
  get wrapped(): boolean {
    return this._wrapped
  }

  /** Sub-sample fraction of our wrap: samples elapsed since the wrap instant, in [0,1). Valid when wrapped. */
  get wrapFrac(): number {
    return this._wrapFrac
  }

  setWave(w: number): void {
    let wi = Math.floor(w)
    if (!Number.isFinite(wi) || wi < 0) wi = 0
    else if (wi > 2) wi = 2
    if (wi === this.wave) return
    this.prevWave = this.wave
    this.wave = wi
    this.fadeCount = this.fadeLen
  }

  /** Continuous SHAPE knob, 0..1 (clamped, smoothed internally). */
  setShape(s: number): void {
    if (!Number.isFinite(s)) return
    this.shapeTarget = s < 0 ? 0 : s > 1 ? 1 : s
  }

  /** Base frequency in Hz, clamped to [0.01, sampleRate*0.45]. */
  setFreq(hz: number): void {
    if (!Number.isFinite(hz)) return
    this.freqTarget = hz < 0.01 ? 0.01 : hz > this.maxFreq ? this.maxFreq : hz
  }

  /**
   * Oscillator-sync reset requested by a master oscillator. wrapFrac is the
   * sub-sample fraction (0..1) of the master's wrap: samples elapsed since the
   * master's wrap instant at the master's current output sample. Call this
   * after master.tick() and before our tick() for the same sample.
   */
  hardSync(wrapFrac: number): void {
    let f = wrapFrac
    if (!Number.isFinite(f)) f = 0
    else if (f < 0) f = 0
    else if (f > 0.99999) f = 0.99999
    this.syncPending = true
    this.syncFrac = f
  }

  reset(phase = 0): void {
    this.phase = Number.isFinite(phase) ? frac(phase) : 0
    this.freqSm = this.freqTarget
    this.shapeSm = this.shapeTarget
    this.fadeCount = 0
    this.syncPending = false
    this._wrapped = false
    this._wrapFrac = 0
    this.lp = 0
    this.chopParity = 1
  }

  /**
   * Advance one sample. fmHz is linear FM (cross-mod input) added to the
   * smoothed base frequency; any finite magnitude is accepted (the effective
   * frequency is clamped to +/- 0.45*sampleRate, non-finite values ignored).
   * Negative effective frequency runs the phase backwards. Returns ~[-1, 1].
   */
  tick(fmHz = 0): number {
    // Parameter smoothing (zipper-free knob moves).
    this.freqSm += this.freqCoef * (this.freqTarget - this.freqSm)
    this.shapeSm += this.shapeCoef * (this.shapeTarget - this.shapeSm)
    this.freqSm = flushDenormal(this.freqSm)
    this.shapeSm = flushDenormal(this.shapeSm)

    let fm = fmHz
    if (!Number.isFinite(fm)) fm = 0
    let f = this.freqSm + fm
    if (f > this.maxFreq) f = this.maxFreq
    else if (f < -this.maxFreq) f = -this.maxFreq

    const dt = f * this.invSr
    const adt = dt >= 0 ? dt : -dt
    const shape = this.shapeSm < 0 ? 0 : this.shapeSm > 1 ? 1 : this.shapeSm

    this._wrapped = false
    let out: number

    if (this.syncPending) {
      // Hard-sync reset. The master wrapped syncFrac samples ago, i.e. at time
      // (1 - syncFrac) into our current inter-sample interval.
      this.syncPending = false
      const tau = this.syncFrac
      // Phase we would have reached at the reset instant (naive step height
      // is measured across this discontinuity).
      const pre = frac(this.phase + adt * (1 - tau))
      this.phase = tau * adt
      this._wrapped = true
      this._wrapFrac = tau
      this.chopParity = -this.chopParity
      out = this.sampleBlended(this.phase, adt, false, shape, true, tau, pre)
    } else {
      let p = this.phase + dt
      if (dt >= 0) {
        if (p >= 1) {
          p -= 1
          if (p >= 1 || p < 0) p = frac(p) // float safety
          this._wrapped = true
          let wf = dt > EPS_DT ? p / dt : 0
          if (wf >= 1) wf = 0.99999
          this._wrapFrac = wf
        }
      } else if (p < 0) {
        p += 1
        if (p >= 1 || p < 0) p = frac(p)
        this._wrapped = true
        // Backward wrap: we crossed 0 heading down; time since crossing.
        let wf = (1 - p) / adt
        if (wf >= 1) wf = 0.99999
        else if (wf < 0) wf = 0
        this._wrapFrac = wf
      }
      if (this._wrapped) this.chopParity = -this.chopParity
      this.phase = p
      out = this.sampleBlended(p, adt, dt < 0, shape, false, 0, 0)
    }

    // Analog edge softness (1-pole LP ~18 kHz).
    this.lp += this.lpCoef * (out - this.lp)
    this.lp = flushDenormal(this.lp)
    out = this.lp
    if (!Number.isFinite(out)) {
      out = 0
      this.lp = 0
    } else if (out > 1.5) out = 1.5
    else if (out < -1.5) out = -1.5
    return out
  }

  /** Current wave sample, crossfading from the previous wave after setWave(). */
  private sampleBlended(
    t: number,
    adt: number,
    rev: boolean,
    shape: number,
    sync: boolean,
    syncTau: number,
    pre: number,
  ): number {
    const cur = this.waveSample(this.wave, t, adt, rev, shape, sync, syncTau, pre)
    if (this.fadeCount > 0) {
      const old = this.waveSample(this.prevWave, t, adt, rev, shape, sync, syncTau, pre)
      const x = 1 - this.fadeCount / this.fadeLen // 0 -> 1 over the fade
      this.fadeCount--
      return old + (cur - old) * x
    }
    return cur
  }

  /**
   * MEASURED SAW morph (v4+): the reversal mirror. In doubled-period phase
   * PHI in [0,2), the wave is saw(PHI) except saw(2-PHI) inside (1-w, 1+w):
   * a time-mirror window centered on the alternate tooth boundary — the ramp
   * literally retraces itself through the suppressed reset. w = 0 is exactly
   * the plain saw; w = 0.5 is the measured half-wave-antisymmetric
   * octave-down endpoint. Constant swing, no level compensation. Per-period
   * naive form with the divider parity p (chopParity, flips per wrap; +1
   * periods start at the pristine reset, -1 periods at the mirror boundary):
   *   mirrored(p, t) = p > 0 ? t >= 1-w : t < w
   *   v(p, t) = mirrored ? 1 - 2t : 2t - 1
   * BLEP'd edges per period: the wrap (step computed from the naive values,
   * so the w -> 0 limit degrades smoothly into the plain saw's -2) and the
   * interior mirror edge (step -2(1-2w) at t = 1-w in +1 periods / t = w in
   * -1 periods). Slope flips are left un-BLAMP'd (second-order). Reverse
   * mode mirrors phase and parity; sync uses the naive-step residual — both
   * documented approximations on rare paths, as in the legacy morphs.
   */
  private sawMirrorSample(
    t: number,
    adt: number,
    shape: number,
    rev: boolean,
    sync: boolean,
    syncTau: number,
    pre: number,
  ): number {
    const wRaw = this.sawMirrorWFn!(shape)
    const w = wRaw < 0 ? 0 : wRaw > 0.5 ? 0.5 : wRaw
    let p = this.chopParity
    let u = t
    if (rev && !sync) {
      u = 1 - t
      p = -p
    }
    // the window (1-w, 1+w) is EMPTY at w = 0 — the guard keeps the step
    // evaluation at the exact boundary ph = 1 on the plain-saw side
    const mirrored = (par: number, ph: number): boolean =>
      w > EPS_DT && (par > 0 ? ph >= 1 - w : ph < w)
    const naive = (par: number, ph: number): number => (mirrored(par, ph) ? 1 - 2 * ph : 2 * ph - 1)
    let y = naive(p, u)
    if (adt > EPS_DT) {
      // wrap edge at phase 0/1 — step from the naive values on each side
      if (u < adt) {
        if (!sync) y += (naive(p, 0) - naive(-p, 1)) * blepAfter(u / adt)
      } else if (u > 1 - adt) {
        y += (naive(-p, 0) - naive(p, 1)) * blepBefore((u - 1) / adt)
      }
      // interior mirror edge: t = 1-w in +1 periods, t = w in -1 periods
      if (w > EPS_DT && w < 0.5 - EPS_DT) {
        const step = -2 * (1 - 2 * w)
        const eOwn = p > 0 ? 1 - w : w
        const sOwn = u - eOwn
        if (sOwn >= 0) {
          if (sOwn < adt) y += step * blepAfter(sOwn / adt)
        } else if (sOwn > -adt) {
          y += step * blepBefore(sOwn / adt)
        }
        // the NEXT period's edge can reach back across the wrap when it sits
        // near the period start (the -1 period's edge at w < adt)
        if (p > 0 && w < adt) {
          const s2 = u - (1 + w)
          if (s2 > -adt) y += step * blepBefore(s2 / adt)
        }
      }
    }
    if (sync) {
      // parity already flipped for this period; the pre-reset sample sat in
      // the OLD period (parity -p) at phase pre (approximation: current w)
      y += (naive(p, 0) - naive(-p, pre)) * blepAfter(syncTau)
    }
    return y
  }

  /**
   * One sample of a given wave at phase t. When sync is true, the standard
   * phase-0 edge correction is suppressed and replaced by a BLEP residual
   * scaled by the true naive step across the sync reset (naive(0) - naive(pre))
   * placed syncTau samples in the past. rev mirrors the phase (u = 1 - t) so
   * negative-frequency (backwards) operation stays properly band-limited.
   */
  private waveSample(
    w: number,
    t: number,
    adt: number,
    rev: boolean,
    shape: number,
    sync: boolean,
    syncTau: number,
    pre: number,
  ): number {
    if (sync) rev = false // sync ticks use forward placement (documented approximation)

    if (w === VCO_WAVE.SAW) {
      if (this.sawMirrorWFn) return this.sawMirrorSample(t, adt, shape, rev, sync, syncTau, pre)
      // LEGACY morph (v0-v3 + the other synths): SHAPE subtracts a second
      // BLEP'd saw (spec §4: morph toward a square-ish blend, attenuating
      // EVEN harmonics). The edge offset narrows toward half a period as
      // shape rises, so at max shape the pair is exactly
      // saw(t) - saw(t+0.5) = a square (odd harmonics only).
      const g = shape
      const off = 0.5 + 0.45 * (1 - g)
      // RMS compensation: var(saw - g*saw_off) = (1-g)^2/3 + 4*g*off*(1-off)
      // (saw autocorrelation R(tau) = 1/3 - 2*tau*(1-tau)); normalize back
      // to a plain saw's variance of 1/3 so the sweep keeps ~equal RMS.
      const norm = 1 / Math.sqrt((1 - g) * (1 - g) + 12 * g * off * (1 - off))
      let core: number
      if (!rev) {
        core = sawBl(t, adt, sync) - g * sawBl(frac(t + off), adt, false)
        if (sync) {
          const naive0 = -1 - g * (2 * frac(off) - 1)
          const naivePre = 2 * pre - 1 - g * (2 * frac(pre + off) - 1)
          core += (naive0 - naivePre) * blepAfter(syncTau)
        }
      } else {
        // Time-mirrored: saw(t) = -saw(1-t); second saw offset flips too.
        const u = 1 - t
        core = -(sawBl(u, adt, false) - g * sawBl(frac(u + 1 - off), adt, false))
      }
      return core * norm
    }

    if (w === VCO_WAVE.TRI) {
      // Triangle is symmetric about phase 0.5, so reverse mode needs no mirror.
      let core = triBl(t, adt, sync)
      if (sync) {
        core += (-1 - triNaive(pre)) * blepAfter(syncTau)
      }
      if (this.triDriveFn) {
        // MEASURED model (v4+): single soft fold per peak. Drive g' rises
        // 1 -> 3 across SHAPE (g' = 3 folds the tip exactly to the opposite
        // level: a x3 triangle, as captured at SHAPE max); the output level
        // at the fold ceiling tapers per the profile table. Applied as a
        // waveshaper on the band-limited core — the C¹ knee keeps the added
        // spectrum decaying fast.
        const drive = this.triDriveFn(shape)
        const level = this.triLevelFn ? this.triLevelFn(shape) : 1
        return level * softFold1(drive * core, this.triKnee)
      }
      // LEGACY folder (v0-v3 + the other synths): smooth sine wavefolder,
      // gain 1..8, blended in with shape. sin() is C-inf smooth so the
      // fold's added spectrum decays fast (low aliasing).
      const m = shape
      if (m <= 0.0005) return core
      const foldGain = 1 + 7 * m
      return (1 - m) * core + m * Math.sin(HALF_PI * foldGain * core)
    }

    if (this.sqrDutyFn) {
      // MEASURED model (v4+): constant-swing pulse at the profile's duty
      // table — the hardware keeps a constant ±swing and carries the pulse's
      // real DC (mean = 2d−1) to the VCF; the legacy path's DC removal and
      // peak normalization are both unfaithful. Duty below the BLEP width
      // fades to the measured SHAPE-max silence.
      let pw = this.sqrDutyFn(shape)
      if (!(pw > 0)) return 0
      if (pw > 0.95) pw = 0.95
      const minPw = Math.min(adt, 0.45)
      let fade = 1
      if (minPw > EPS_DT && pw < minPw) {
        fade = pw / minPw
        pw = minPw
      }
      if (!rev) {
        let core = pulseBl(t, adt, pw, sync)
        if (sync) {
          const naivePre = pre < pw ? 1 : -1
          core += (1 - naivePre) * blepAfter(syncTau) // naive(0) = +1
        }
        return core * fade
      }
      // Time-mirrored pulse: pulse(t; pw) = -pulse(1-t; 1-pw).
      return -pulseBl(1 - t, adt, 1 - pw, false) * fade
    }
    // LEGACY SQR (v0-v3 + the other synths): pulse width 50% -> pwMin; both
    // edges BLEP'd; analytic DC removal (dc = 2*pw - 1) and peak
    // normalization so output stays within [-1, 1].
    // Widths below the BLEP transition width can't be rendered: the stock law
    // (pwMin 0.05) clamps there at full amplitude exactly as it always has —
    // that path must stay bit-identical for every synth. Only a calibration
    // profile that asks for a sub-5% floor fades the unrenderable stretch out
    // instead, so pwMin = 0 reaches true silence at SHAPE max like the
    // measured hardware. (The pwMin < minPw gate also keeps the fade
    // denominator strictly positive.)
    let pw = 0.5 - (0.5 - this.pwMin) * shape
    const minPw = Math.max(this.pwMin, Math.min(adt, 0.45))
    let fade = 1
    if (pw < minPw) {
      if (this.pwMin < 0.05 && this.pwMin < minPw) {
        fade = Math.max(0, (pw - this.pwMin) / (minPw - this.pwMin))
      }
      pw = minPw
    } else if (pw > 1 - minPw) pw = 1 - minPw
    const dc = 2 * pw - 1
    const scale = fade / (2 * (1 - pw))
    if (!rev) {
      let core = pulseBl(t, adt, pw, sync)
      if (sync) {
        const naivePre = pre < pw ? 1 : -1
        core += (1 - naivePre) * blepAfter(syncTau) // naive(0) = +1
      }
      return (core - dc) * scale
    }
    // Time-mirrored pulse: pulse(t; pw) = -pulse(1-t; 1-pw).
    const u = 1 - t
    const pw2 = 1 - pw
    const core = pulseBl(u, adt, pw2, false)
    return -(core - (2 * pw2 - 1)) * scale
  }
}
