/*
 * Korg prologue parameter table — single source of truth for every program
 * parameter of the prologue definition (both variants: prologue-8 and
 * prologue-16 programs are format-identical, spec §14). Ids are stable and
 * append-only; raw ranges mirror the hardware (docs/prologue-spec.md §2,
 * MIDIimp TABLE 3).
 *
 * Layout — the prologue is BITIMBRAL (spec §2): program-global params first
 * (ids 0..GLOBAL_PARAM_COUNT-1, stored once per program), then two identical
 * per-timbre blocks generated by the timbreDefs factory (TIMBRE 1 = MAIN,
 * TIMBRE 2 = SUB). Timbre params get keys 't1'/'t2' + capitalized base key
 * ('t1Vco1Wave') and labels 'T1 '/'T2 ' + base label ('T1 VCO1 WAVE').
 * Engine/panel/CC code addresses timbre params through TIMBRE_BLOCKS
 * (semantic name -> param id per timbre) — never through key-string math.
 * Three replica-only params (RP: L.F. COMP ON/GAIN + VOICE CAP, documented
 * deviations) are appended after the timbre blocks.
 *
 * Name-level fields (program name) live outside params as usual; TEMPO lives
 * in Program.seq.bpm (spec §15 — one transport tempo, the arp reads it).
 * CATEGORY/FREQUENT/LIKE sort metadata and the USER ENGINE PARAM1-6 slots
 * are out of scope (implementation-notes.md: user slots ship built-ins).
 *
 * Motion recordability: the prologue has NO step sequencer and NO motion
 * sequencing (spec §10) — every param is motion: false; MOTION_PARAM_IDS
 * carries only the two virtual targets and the StepSeq stays dormant.
 *
 * Factory init defaults are UNCONFIRMED (no hardware program dump available);
 * values below are the replica's musically-neutral init, mirroring the
 * family tables.
 */
import {
  type ParamMeta,
  type MotionTargetMeta,
  knob,
  sw,
  menu,
  buildParamTable,
  clampParamIn,
  formatParamIn,
  motionParamIdsOf,
  motionParamLabelIn,
  motionMetaFor,
} from '../../shared/paramdef'
import { fmtSec, fmtHz, fmtDb } from '../../shared/maps'
import * as curves from './curves'
import {
  MODFX_TYPES,
  CHORUS_SUBS,
  ENSEMBLE_SUBS,
  PHASER_SUBS,
  FLANGER_SUBS,
  USER_MODFX_SUBS,
  DELAY_SUBS,
  REVERB_SUBS,
  ARP_TYPES,
  ARP_RATES,
  WHEEL_ASSIGN_DESTS,
  MICRO_TUNINGS,
} from './curves'

// ---------------------------------------------------------------------------
// Program-global params (MIDIimp TABLE 3 bytes 16..79)
// ---------------------------------------------------------------------------
export const P = {
  OCTAVE: 0,
  SUB_ON: 1,
  EDIT_TIMBRE: 2,
  TIMBRE_TYPE: 3,
  BALANCE: 4,
  POSITION: 5,
  SPLIT_POINT: 6,
  AMP_VELOCITY: 7,
  PORTAMENTO_MODE: 8,
  PROGRAM_LEVEL: 9,
  PROGRAM_TUNING: 10,
  PROGRAM_TRANSPOSE: 11,
  MICRO_TUNING: 12,
  SCALE_KEY: 13,
  MODFX_ON: 14,
  MODFX_TYPE: 15,
  MODFX_SUB_CHORUS: 16,
  MODFX_SUB_ENSEMBLE: 17,
  MODFX_SUB_PHASER: 18,
  MODFX_SUB_FLANGER: 19,
  MODFX_SUB_USER: 20,
  MODFX_SPEED: 21,
  MODFX_DEPTH: 22,
  MODFX_ROUTING: 23,
  DLRV_SELECT: 24,
  DELAY_SUB: 25,
  REVERB_SUB: 26,
  DLRV_TIME: 27,
  DLRV_DEPTH: 28,
  DLRV_DRYWET: 29,
  DLRV_ON: 30,
  DLRV_ROUTING: 31,
  ARP_ON_LATCH: 32,
  ARP_TYPE: 33,
  ARP_RANGE: 34,
  ARP_RATE: 35,
  ARP_GATE: 36,
  ARP_TARGET: 37,
} as const

export type GlobalParamId = (typeof P)[keyof typeof P]
export const GLOBAL_PARAM_COUNT = 38

const WAVES = ['SQR', 'TRI', 'SAW'] as const
/** VCO/MULTI octave, program-data enum order (MIDIimp timbre +11/+20/+30 and
 *  CC notes *2-01/*5-01 all print 2'->16'). NOTE: REVERSED relative to the
 *  xd/OG/monologue program enums — a family-doc inconsistency; the prologue
 *  doc is self-consistent in three places so we follow it (verify on
 *  hardware, spec §17-class). */
const OCTAVES = ["2'", "4'", "8'", "16'"] as const
const ONOFF = ['Off', 'On'] as const
const PCT3 = ['0%', '50%', '100%'] as const
/** FX/arp routing, program-data enum order (bytes 26/69/70). */
const ROUTINGS = ['Main+Sub', 'Main', 'Sub'] as const

/** SYNC/RING exclusive 3-position switch, timbre byte +25 order
 *  (0=RING ON, 1=OFF, 2=SYNC ON — CROSS MOD stacks with either, spec §3). */
const SYNC_RING_MODES = ['RING', 'OFF', 'SYNC'] as const

/** PITCH EG switch, OM panel order [VCO 2, VCO 1+2, ALL(+multi)] (spec §3).
 *  UNCONFIRMED enum order: the MIDIimp prints byte +16 as 0~2=VCO1,+,VCO2 and
 *  the CC81 zones as VCO1/VCO1+2/VCO2 — spec §16.6, reconcile on hardware. */
const PITCH_EG_TARGETS = ['VCO 2', 'VCO 1+2', 'ALL'] as const

/** LFO MODE, timbre byte +71 order (0=BPM, 1=SLOW, 2=FAST — no 1-shot). */
const LFO_MODES = ['BPM', 'SLOW', 'FAST'] as const

/** VOICE MODE TYPE, timbre byte +6 order (MIDIimp note P14). */
const VOICE_MODES = ['POLY', 'MONO', 'UNISON', 'CHORD'] as const

const NOISE_TYPES = ['High', 'Low', 'Peak', 'Decim'] as const
const VPM_TYPES = [
  'Sin1', 'Sin2', 'Sin3', 'Sin4', 'Saw1', 'Saw2', 'Squ1', 'Squ2',
  'Fat1', 'Fat2', 'Air1', 'Air2', 'Decay1', 'Decay2', 'Creep', 'Throat',
] as const
/** Replica user-osc slots (the hardware has 16 empty slots; we ship the
 *  family's four built-ins — implementation-notes.md, out-of-scope list). */
const USER_OSCS = ['MORPH', 'SPRSAW', 'PWMCLS', 'ORGAN'] as const

function fmtBipolar200(r: number): string {
  const v = r - 100
  return (v > 0 ? '+' : '') + v + '%'
}

const GLOBAL_DEFS: ParamMeta[] = [
  menu(P.OCTAVE, 'octave', 'KBD OCTAVE', 0, 4, 2, { labels: ['-2', '-1', '0', '+1', '+2'] }),
  // Byte 17 prints "0,1=SUB ON,PGM FETCH" — read as the sub-timbre enable
  // (SUB ON halves the voice pool, spec §1); UNCONFIRMED interpretation.
  sw(P.SUB_ON, 'subOn', 'SUB ON', ONOFF, 0),
  // Byte 18 order 0~2=Main,Main+Sub,Sub. NOTE: CC85 zones arrive in the
  // REVERSE order (SUB/+/MAIN) — handled in cc.ts.
  sw(P.EDIT_TIMBRE, 'editTimbre', 'EDIT TIMBRE', ['Main', 'Main+Sub', 'Sub'], 0),
  sw(P.TIMBRE_TYPE, 'timbreType', 'TIMBRE TYPE', ['LAYER', 'XFADE', 'SPLIT'], 0),
  menu(P.BALANCE, 'balance', 'MAIN/SUB BALANCE', 0, 127, 64),
  menu(P.POSITION, 'position', 'MAIN/SUB POSITION', 0, 1, 0, { labels: ['Sub<>Main', 'Main<>Sub'] }),
  // 0..127 = C-1..G9 (byte 23); default C4 UNCONFIRMED.
  menu(P.SPLIT_POINT, 'splitPoint', 'SPLIT POINT', 0, 127, 60, { fmt: curves.noteName }),
  menu(P.AMP_VELOCITY, 'ampVelocity', 'AMP VELOCITY', 0, 127, 64),
  menu(P.PORTAMENTO_MODE, 'portamentoMode', 'PORTAMENTO MODE', 0, 1, 0, { labels: ['Auto', 'On'] }),
  // Stored 12..132 = -18..+6 dB (0.2 dB steps), 102 = 0 dB (byte 40).
  menu(P.PROGRAM_LEVEL, 'programLevel', 'PROGRAM LEVEL', 12, 132, 102, {
    fmt: (r) => fmtDb(curves.programLevelToDb(r)),
  }),
  menu(P.PROGRAM_TUNING, 'programTuning', 'PROGRAM TUNING', 0, 100, 50, {
    fmt: (r) => (r - 50 > 0 ? '+' : '') + (r - 50) + 'C',
  }),
  menu(P.PROGRAM_TRANSPOSE, 'programTranspose', 'TRANSPOSE', 0, 24, 12, {
    fmt: (r) => (r - 12 > 0 ? '+' : '') + (r - 12) + ' Note',
  }),
  // Replica ships the family preset subset, not the hardware's user slots.
  menu(P.MICRO_TUNING, 'microTuning', 'MICROTUNING', 0, MICRO_TUNINGS.length - 1, 0, {
    labels: MICRO_TUNINGS.map((t) => t.name),
  }),
  menu(P.SCALE_KEY, 'scaleKey', 'SCALE KEY', 0, 24, 12, {
    fmt: (r) => (r - 12 > 0 ? '+' : '') + (r - 12) + ' Note',
  }),
  sw(P.MODFX_ON, 'modFxOn', 'MOD FX', ONOFF, 0),
  sw(P.MODFX_TYPE, 'modFxType', 'MOD FX TYPE', MODFX_TYPES, 0),
  sw(P.MODFX_SUB_CHORUS, 'modFxSubChorus', 'CHORUS', CHORUS_SUBS, 0),
  sw(P.MODFX_SUB_ENSEMBLE, 'modFxSubEnsemble', 'ENSEMBLE', ENSEMBLE_SUBS, 0),
  sw(P.MODFX_SUB_PHASER, 'modFxSubPhaser', 'PHASER', PHASER_SUBS, 0),
  sw(P.MODFX_SUB_FLANGER, 'modFxSubFlanger', 'FLANGER', FLANGER_SUBS, 0),
  sw(P.MODFX_SUB_USER, 'modFxSubUser', 'USER FX', USER_MODFX_SUBS, 0),
  knob(P.MODFX_SPEED, 'modFxSpeed', 'MOD FX SPEED', 512),
  knob(P.MODFX_DEPTH, 'modFxDepth', 'MOD FX DEPTH', 512),
  menu(P.MODFX_ROUTING, 'modFxRouting', 'MOD FX ROUTING', 0, 2, 0, { labels: ROUTINGS }),
  // The panel's 3-way EFFECT switch (byte 62): DELAY and REVERB are mutually
  // exclusive (spec §7).
  sw(P.DLRV_SELECT, 'dlRvSelect', 'DELAY/REVERB', ['OFF', 'DELAY', 'REVERB'], 0),
  sw(P.DELAY_SUB, 'delaySub', 'DELAY TYPE', DELAY_SUBS, 0),
  sw(P.REVERB_SUB, 'reverbSub', 'REVERB TYPE', REVERB_SUBS, 0),
  knob(P.DLRV_TIME, 'dlRvTime', 'DL/RV TIME', 512),
  knob(P.DLRV_DEPTH, 'dlRvDepth', 'DL/RV DEPTH', 512),
  // FW2 DRY WET, stored 1..1025 on hardware (bytes 57-58); the replica strips
  // the 1-offset like the family's other 1-based menus: 0..1024, 512 = center.
  knob(P.DLRV_DRYWET, 'dlRvDryWet', 'DL/RV DRY/WET', 512, {
    max: 1024,
    fmt: (r) => Math.round((r / 1024) * 100) + '%',
  }),
  // Byte 72 ON/OFF, separate from the 3-way select; default On so the panel
  // select alone gates the effect (UNCONFIRMED factory value).
  sw(P.DLRV_ON, 'dlRvOn', 'DL/RV ON', ONOFF, 1),
  menu(P.DLRV_ROUTING, 'dlRvRouting', 'DL/RV ROUTING', 0, 2, 0, { labels: ROUTINGS }),
  sw(P.ARP_ON_LATCH, 'arpOnLatch', 'ARPEGGIATOR', ['Off', 'On', 'Latch'], 0),
  menu(P.ARP_TYPE, 'arpType', 'ARP TYPE', 0, ARP_TYPES.length - 1, 1, { labels: ARP_TYPES }),
  menu(P.ARP_RANGE, 'arpRange', 'ARP RANGE', curves.ARP_RANGE_MIN, curves.ARP_RANGE_MAX, 1, {
    fmt: (r) => Math.round(r) + ' Oct',
  }),
  menu(P.ARP_RATE, 'arpRate', 'ARP RATE', 0, ARP_RATES.length - 1, 4, { labels: ARP_RATES.map((r) => r.label) }),
  // Hardware stores 1..73 = 0..100% (byte 55); the replica strips the
  // 1-offset like the xd's table: 0..72.
  menu(P.ARP_GATE, 'arpGate', 'ARP GATE TIME', 0, 72, 54, { fmt: (r) => Math.round((r / 72) * 100) + '%' }),
  menu(P.ARP_TARGET, 'arpTarget', 'ARP TARGET', 0, 2, 0, { labels: ROUTINGS }),
]

// ---------------------------------------------------------------------------
// Per-timbre block (MIDIimp TABLE 3, 126-byte blocks at 80/206) — one spec
// list drives BOTH the ParamMeta defs and the TIMBRE_BLOCKS id map, so the
// two can't drift. Spec order follows the timbre byte layout.
// ---------------------------------------------------------------------------
interface TimbreSpec {
  /** Semantic accessor name (TIMBRE_BLOCKS field) and base of the t1/t2 key. */
  readonly name: string
  /** OLED label base ('VCO1 WAVE' -> 'T1 VCO1 WAVE' / 'T2 VCO1 WAVE'). */
  readonly label: string
  readonly make: (id: number, key: string, label: string) => ParamMeta
}

const TIMBRE_SPECS = [
  // --- master block (timbre bytes +0..+6) ---------------------------------
  { name: 'portamento', label: 'PORTAMENTO', make: (id, key, label) => menu(id, key, label, 0, 127, 0, { fmt: (r) => (r <= 0 ? 'Off' : String(Math.round(r))) }) },
  { name: 'voiceSpread', label: 'VOICE SPREAD', make: (id, key, label) => menu(id, key, label, 0, 127, 0) },
  { name: 'vmDepth', label: 'VOICE MODE DEPTH', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'voiceMode', label: 'VOICE MODE', make: (id, key, label) => sw(id, key, label, VOICE_MODES, 0) },
  // --- VCO 1 / PITCH EG / VCO 2 (+10..+24) --------------------------------
  { name: 'vco1Wave', label: 'VCO1 WAVE', make: (id, key, label) => sw(id, key, label, WAVES, 2) },
  { name: 'vco1Octave', label: 'VCO1 OCTAVE', make: (id, key, label) => sw(id, key, label, OCTAVES, 2) },
  { name: 'vco1Pitch', label: 'VCO1 PITCH', make: (id, key, label) => knob(id, key, label, 512, { fmt: curves.fmtCents }) },
  { name: 'vco1Shape', label: 'VCO1 SHAPE', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'pitchEgTarget', label: 'PITCH EG', make: (id, key, label) => sw(id, key, label, PITCH_EG_TARGETS, 0) },
  { name: 'pitchEgInt', label: 'PITCH EG INT', make: (id, key, label) => knob(id, key, label, 512, { fmt: curves.fmtPitchEgInt }) },
  { name: 'vco2Wave', label: 'VCO2 WAVE', make: (id, key, label) => sw(id, key, label, WAVES, 2) },
  { name: 'vco2Octave', label: 'VCO2 OCTAVE', make: (id, key, label) => sw(id, key, label, OCTAVES, 2) },
  { name: 'vco2Pitch', label: 'VCO2 PITCH', make: (id, key, label) => knob(id, key, label, 512, { fmt: curves.fmtCents }) },
  { name: 'vco2Shape', label: 'VCO2 SHAPE', make: (id, key, label) => knob(id, key, label, 0) },
  // --- modulation (+25..+27) ----------------------------------------------
  { name: 'syncRing', label: 'SYNC/RING', make: (id, key, label) => sw(id, key, label, SYNC_RING_MODES, 1) },
  { name: 'crossMod', label: 'CROSS MOD DEPTH', make: (id, key, label) => knob(id, key, label, 0) },
  // --- multi engine (+28..+35, +107..+114; no SHIFT-SHAPE-NOISE, spec §6:
  //     timbre bytes +36-37 are reserved) ----------------------------------
  { name: 'multiRouting', label: 'MULTI ROUTING', make: (id, key, label) => menu(id, key, label, 0, 1, 0, { labels: ['Pre VCF', 'Post VCF'] }) },
  { name: 'multiType', label: 'MULTI TYPE', make: (id, key, label) => sw(id, key, label, ['NOISE', 'VPM', 'USR'], 1) },
  { name: 'multiOctave', label: 'MULTI OCTAVE', make: (id, key, label) => sw(id, key, label, OCTAVES, 2) },
  { name: 'selectNoise', label: 'NOISE TYPE', make: (id, key, label) => sw(id, key, label, NOISE_TYPES, 0) },
  { name: 'selectVpm', label: 'VPM TYPE', make: (id, key, label) => sw(id, key, label, VPM_TYPES, 0) },
  { name: 'selectUser', label: 'USER OSC', make: (id, key, label) => sw(id, key, label, USER_OSCS, 0) },
  { name: 'shapeNoise', label: 'MULTI SHAPE', make: (id, key, label) => knob(id, key, label, 512) },
  { name: 'shapeVpm', label: 'MULTI SHAPE', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'shapeUser', label: 'MULTI SHAPE', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'shiftShapeVpm', label: 'SHIFT SHAPE', make: (id, key, label) => knob(id, key, label, 512) },
  { name: 'shiftShapeUser', label: 'SHIFT SHAPE', make: (id, key, label) => knob(id, key, label, 0) },
  // --- mixer (+38..+43) ---------------------------------------------------
  { name: 'vco1Level', label: 'VCO1 LEVEL', make: (id, key, label) => knob(id, key, label, 1023) },
  { name: 'vco2Level', label: 'VCO2 LEVEL', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'multiLevel', label: 'MULTI LEVEL', make: (id, key, label) => knob(id, key, label, 0) },
  // --- filter (+44..+53) --------------------------------------------------
  { name: 'cutoff', label: 'CUTOFF', make: (id, key, label) => knob(id, key, label, 1023, { fmt: (r) => fmtHz(curves.cutoffToHz(r)) }) },
  { name: 'resonance', label: 'RESONANCE', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'cutoffEgInt', label: 'CUTOFF EG INT', make: (id, key, label) => knob(id, key, label, 512, { fmt: curves.fmtEgInt }) },
  { name: 'drive', label: 'DRIVE', make: (id, key, label) => sw(id, key, label, PCT3, 0) },
  { name: 'lowCut', label: 'LOW CUT', make: (id, key, label) => sw(id, key, label, ONOFF, 0) },
  { name: 'keytrack', label: 'KEYTRACK', make: (id, key, label) => sw(id, key, label, PCT3, 0) },
  // Hardware name: CUTOFF VELOCITY (byte +53) — scales the cutoff-EG int
  // (spec §5); family label EG VELOCITY.
  { name: 'egVelocity', label: 'EG VELOCITY', make: (id, key, label) => menu(id, key, label, 0, 127, 0) },
  // --- envelopes (+54..+69) -----------------------------------------------
  { name: 'ampAttack', label: 'AMP EG ATTACK', make: (id, key, label) => knob(id, key, label, 0, { fmt: (r) => fmtSec(curves.attackToSec(r)) }) },
  { name: 'ampDecay', label: 'AMP EG DECAY', make: (id, key, label) => knob(id, key, label, 200, { fmt: (r) => fmtSec(curves.decayToSec(r)) }) },
  { name: 'ampSustain', label: 'AMP EG SUSTAIN', make: (id, key, label) => knob(id, key, label, 1023) },
  { name: 'ampRelease', label: 'AMP EG RELEASE', make: (id, key, label) => knob(id, key, label, 100, { fmt: (r) => fmtSec(curves.releaseToSec(r)) }) },
  { name: 'egAttack', label: 'EG ATTACK', make: (id, key, label) => knob(id, key, label, 0, { fmt: (r) => fmtSec(curves.attackToSec(r)) }) },
  { name: 'egDecay', label: 'EG DECAY', make: (id, key, label) => knob(id, key, label, 300, { fmt: (r) => fmtSec(curves.decayToSec(r)) }) },
  { name: 'egSustain', label: 'EG SUSTAIN', make: (id, key, label) => knob(id, key, label, 0) },
  { name: 'egRelease', label: 'EG RELEASE', make: (id, key, label) => knob(id, key, label, 0, { fmt: (r) => fmtSec(curves.releaseToSec(r)) }) },
  // --- LFO (+70..+76, +116..+118) -----------------------------------------
  { name: 'lfoWave', label: 'LFO WAVE', make: (id, key, label) => sw(id, key, label, WAVES, 1) },
  { name: 'lfoMode', label: 'LFO MODE', make: (id, key, label) => sw(id, key, label, LFO_MODES, 1) },
  // fmt shows the SLOW-range Hz; the engine picks the curve per LFO MODE
  // (curves.lfoRateToHz) — a static fmt can't see the mode here.
  { name: 'lfoRate', label: 'LFO RATE', make: (id, key, label) => knob(id, key, label, 512, { fmt: (r) => fmtHz(curves.lfoSlowHz(r)) }) },
  // Bipolar center-512 store; panel INT 0..511 + SHIFT = invert (spec §8).
  { name: 'lfoInt', label: 'LFO INT', make: (id, key, label) => knob(id, key, label, 512, { fmt: curves.fmtLfoInt }) },
  { name: 'lfoTarget', label: 'LFO TARGET', make: (id, key, label) => sw(id, key, label, ['CUTOFF', 'SHAPE', 'PITCH'], 2) },
  { name: 'lfoTargetOsc', label: 'LFO TARGET OSC', make: (id, key, label) => menu(id, key, label, 0, 3, 0, { labels: ['All', 'VCO1+2', 'VCO2', 'Multi'] }) },
  { name: 'lfoKeySync', label: 'LFO KEY SYNC', make: (id, key, label) => menu(id, key, label, 0, 1, 0, { labels: ONOFF }) },
  { name: 'lfoVoiceSync', label: 'LFO VOICE SYNC', make: (id, key, label) => menu(id, key, label, 0, 1, 0, { labels: ONOFF }) },
  // --- wheel / aftertouch / bend (+77, +115, +120, +79/+80) ---------------
  // Hardware stores +77 as 2~32 against note P23's 32-entry 0..31 list — an
  // off-by-one doc quirk; the replica stores the clean P23 index 0..31.
  // Default LFO INT (wheel vibrato) UNCONFIRMED.
  { name: 'wheelAssign', label: 'M.WHEEL ASSIGN', make: (id, key, label) => menu(id, key, label, 0, WHEEL_ASSIGN_DESTS.length - 1, 26, { labels: WHEEL_ASSIGN_DESTS }) },
  { name: 'wheelRange', label: 'M.WHEEL RANGE', make: (id, key, label) => menu(id, key, label, 0, 200, 200, { fmt: fmtBipolar200 }) },
  // FW 2.00 MIDI aftertouch assign (receive-only, spec §9); default CUTOFF
  // UNCONFIRMED.
  { name: 'atAssign', label: 'MIDI AFTERTOUCH', make: (id, key, label) => menu(id, key, label, 0, WHEEL_ASSIGN_DESTS.length - 1, 14, { labels: WHEEL_ASSIGN_DESTS }) },
  { name: 'bendRangePlus', label: 'BEND RANGE +', make: (id, key, label) => menu(id, key, label, 0, 12, 2, { fmt: (r) => (r === 0 ? 'Off' : '+' + r) }) },
  { name: 'bendRangeMinus', label: 'BEND RANGE -', make: (id, key, label) => menu(id, key, label, 0, 12, 2, { fmt: (r) => (r === 0 ? 'Off' : '-' + r) }) },
  // Hardware name: MONO LEGATO (byte +119) — EG legato for the mono-family
  // voice modes (spec §4); family label EG LEGATO.
  { name: 'egLegato', label: 'EG LEGATO', make: (id, key, label) => menu(id, key, label, 0, 1, 0, { labels: ONOFF }) },
  // --- VPM engine menu params (+81..+91) ----------------------------------
  // Hardware names them VPM ENGINE PARAM1-6; the PARAM1-6 <-> VpmTrims field
  // order is UNCONFIRMED (spec §17) — assumed to match the xd's menu order.
  { name: 'vpmFeedback', label: 'VPM FEEDBACK', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
  { name: 'vpmNoiseDepth', label: 'VPM NOISE DEPTH', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
  { name: 'vpmShapeModInt', label: 'VPM SHAPE MOD INT', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
  { name: 'vpmModAttack', label: 'VPM MOD ATTACK', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
  { name: 'vpmModDecay', label: 'VPM MOD DECAY', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
  { name: 'vpmKeyTrack', label: 'VPM KEY TRACK', make: (id, key, label) => menu(id, key, label, 0, 200, 100, { fmt: fmtBipolar200 }) },
] as const satisfies readonly TimbreSpec[]

/** Semantic timbre-param names (the TIMBRE_BLOCKS accessor surface). */
export type TimbreKey = (typeof TIMBRE_SPECS)[number]['name']

/** One timbre block's param ids, keyed by semantic name. */
export type TimbreParamIds = { readonly [K in TimbreKey]: number }

export const TIMBRE_PARAM_COUNT = TIMBRE_SPECS.length
/** Replica-only params appended AFTER the two timbre blocks (see RP below). */
export const REPLICA_PARAM_COUNT = 3
export const PARAM_COUNT = GLOBAL_PARAM_COUNT + 2 * TIMBRE_PARAM_COUNT + REPLICA_PARAM_COUNT

/** Generate one timbre block: defs (keys 't<n>' + capitalized base, labels
 *  'T<n> ' + base) plus the semantic-name -> id map, from one spec list. */
function timbreDefs(t: 1 | 2, baseId: number): { defs: ParamMeta[]; ids: TimbreParamIds } {
  const defs: ParamMeta[] = []
  const ids: Record<string, number> = {}
  for (let i = 0; i < TIMBRE_SPECS.length; i++) {
    const s = TIMBRE_SPECS[i]
    const id = baseId + i
    ids[s.name] = id
    const key = 't' + t + s.name.charAt(0).toUpperCase() + s.name.slice(1)
    defs.push(s.make(id, key, 'T' + t + ' ' + s.label))
  }
  return { defs, ids: ids as TimbreParamIds }
}

const T1 = timbreDefs(1, GLOBAL_PARAM_COUNT)
const T2 = timbreDefs(2, GLOBAL_PARAM_COUNT + TIMBRE_PARAM_COUNT)

/** Per-timbre param ids ([0] = TIMBRE 1 / MAIN, [1] = TIMBRE 2 / SUB) —
 *  engine/panel/CC code loops over timbres through this, never key strings. */
export const TIMBRE_BLOCKS: readonly [TimbreParamIds, TimbreParamIds] = [T1.ids, T2.ids]

// ---------------------------------------------------------------------------
// Replica-only params — documented DEVIATIONS from hardware program data,
// appended AFTER the two timbre blocks so the hardware-faithful ids 0..167
// never move (append-only). They serialize by key like everything else:
//   - L.F. COMP (prologue-16, spec §7): a physical panel section with zero
//     program/MIDI presence on hardware ("not stored in programs"); the
//     replica stores ON + GAIN as ordinary params — simplest and honest.
//   - VOICE CAP: pure replica config with no hardware analog — the
//     prologue-8 variant runs the same 16-voice engine capped to 8
//     (spec §14), and spec §15's low-end fallback caps further. The engine
//     never allocates voice indices >= cap; the bank stays 16 wide.
// ---------------------------------------------------------------------------
const RP_BASE = GLOBAL_PARAM_COUNT + 2 * TIMBRE_PARAM_COUNT
export const RP = {
  LF_COMP_ON: RP_BASE,
  LF_COMP_GAIN: RP_BASE + 1,
  VOICE_CAP: RP_BASE + 2,
} as const

const REPLICA_DEFS: ParamMeta[] = [
  sw(RP.LF_COMP_ON, 'lfCompOn', 'L.F. COMP', ONOFF, 0),
  // GAIN default 0 = no low boost when switched on (neutral; the hardware
  // knob's detent behavior is UNCONFIRMED — dsp/fx/lfcomp.ts voicing too).
  knob(RP.LF_COMP_GAIN, 'lfCompGain', 'L.F. COMP GAIN', 0),
  menu(RP.VOICE_CAP, 'voiceCap', 'VOICE CAP', 1, 16, 16, {
    fmt: (r) => Math.round(r) + ' VOICE',
  }),
]

// No motion sequencing on the prologue (spec §10): strip the factories'
// default motion: true from every param in one place.
const DEFS: ParamMeta[] = [...GLOBAL_DEFS, ...T1.defs, ...T2.defs, ...REPLICA_DEFS].map((m) =>
  m.motion ? { ...m, motion: false } : m
)

export const PARAMS: readonly ParamMeta[] = buildParamTable(DEFS, PARAM_COUNT)

export const PARAM_BY_KEY: ReadonlyMap<string, ParamMeta> = new Map(PARAMS.map((p) => [p.key, p]))

export function clampParam(id: number, v: number): number {
  return clampParamIn(PARAMS, id, v)
}

export function formatParam(id: number, v: number): string {
  return formatParamIn(PARAMS, id, v)
}

/** Motion targets: no program params (spec §10 — no motion sequencing), only
 *  the two virtual ids remain; the StepSeq stays constructed-but-dormant. */
export const MOTION_PARAM_IDS: readonly number[] = motionParamIdsOf(PARAMS)

export function motionParamLabel(id: number): string {
  return motionParamLabelIn(PARAMS, id)
}

/** Motion-target predicates for the StepSeq core, bound to this table. */
export const MOTION_META: MotionTargetMeta = motionMetaFor(PARAMS)

// ---------------------------------------------------------------------------
// M.WHEEL / aftertouch destination -> param id (WHEEL_ASSIGN_DESTS order,
// curves.ts; per-timbre assign). Lives here rather than in curves.ts so
// curves stays import-free of the id tables (no cycle) — the og/mono
// sliderDestParam precedent.
// ---------------------------------------------------------------------------

/** Virtual destination: offsets the sequencer/arp gate time (the family
 *  GATE TIME layer; og SLIDER_DEST_GATE_TIME precedent). */
export const WHEEL_DEST_GATE_TIME = -2
/** Engine-dependent destination: resolves to the timbre's active MULTI
 *  TYPE's shape param (the xd JOY_DEST_IDS -2 precedent, synths/xd/engine.ts). */
export const WHEEL_DEST_MULTI_SHAPE = -3

function wheelDestIds(t: TimbreParamIds): readonly number[] {
  return [
    P.BALANCE, // BALANCE (program-global — a real param, no sentinel needed)
    t.portamento,
    t.voiceSpread,
    t.vmDepth,
    t.vco1Pitch,
    t.vco1Shape,
    t.vco2Pitch,
    t.vco2Shape,
    t.crossMod,
    t.pitchEgInt,
    WHEEL_DEST_MULTI_SHAPE, // MULTI SHAPE (per active MULTI TYPE)
    t.vco1Level,
    t.vco2Level,
    t.multiLevel,
    t.cutoff,
    t.resonance,
    t.cutoffEgInt,
    t.ampAttack,
    t.ampDecay,
    t.ampSustain,
    t.ampRelease,
    t.egAttack,
    t.egDecay,
    t.egSustain,
    t.egRelease,
    t.lfoRate,
    t.lfoInt,
    P.MODFX_SPEED, // program-global FX params
    P.MODFX_DEPTH,
    P.DLRV_TIME,
    P.DLRV_DEPTH,
    WHEEL_DEST_GATE_TIME, // GATE TIME (virtual)
  ]
}

const WHEEL_DEST_IDS: readonly (readonly number[])[] = [wheelDestIds(T1.ids), wheelDestIds(T2.ids)]

/** Param id for a wheel/aftertouch destination index 0..31 on a timbre
 *  (0 = MAIN, 1 = SUB); negative = virtual/engine-dependent
 *  (WHEEL_DEST_GATE_TIME / WHEEL_DEST_MULTI_SHAPE). */
export function wheelDestParam(destIndex: number, timbre: number): number {
  const t = WHEEL_DEST_IDS[timbre >= 1 ? 1 : 0]
  const i = Math.max(0, Math.min(t.length - 1, Math.round(destIndex)))
  return t[i]
}
